version: '3.4'

services:
  app:
    image: munaiplan-backend-app
    container_name: munaiplan-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
      - ./internal/catalog/catalog_files/:/root/catalog_files/
    env_file:
      - .env


  mongodb:
    image: mongo:4.4-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=munaiPlan
      - MONGO_INITDB_ROOT_USERNAME=myAdminUser
      - MONGO_INITDB_ROOT_PASSWORD=myAdminPassword
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017