http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

mongo:
  databaseName: munaiPlan

catalogCache:
  apiDrillCollarPath: "/Users/kadirbeksharau/Desktop/MunaiPlan/munaiplan-backend/API Drill Collar.cat.xml"