// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/companies": {
            "get": {
                "description": "Retrieves all companies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Get Companies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Company"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Create Company",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Company input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/companies/{id}": {
            "put": {
                "description": "Updates an existing company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Update Company",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Company input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Company"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Delete Company",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/companies/{name}": {
            "get": {
                "description": "Retrieves a company by its name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Get Company by Name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Company Name",
                        "name": "companyName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Company"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/designs": {
            "get": {
                "description": "Retrieves all designs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "Get Designs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wellbore ID",
                        "name": "wellboreId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Design"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new design",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "Create Design",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wellbore ID",
                        "name": "wellboreId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Design input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateDesignRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/designs/{id}": {
            "get": {
                "description": "Retrieves a design by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "Get Design by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Design ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Design"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing design",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "Update Design",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Design ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Design input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateDesignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Design"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing design",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "designs"
                ],
                "summary": "Delete Design",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Design ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/fields": {
            "get": {
                "description": "Retrieves all fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fields"
                ],
                "summary": "Get Fields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "companyId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Field"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new field",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fields"
                ],
                "summary": "Create Field",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "companyId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Field input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateFieldRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/fields/{id}": {
            "get": {
                "description": "Retrieves a field by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fields"
                ],
                "summary": "Get Field by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Field ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Field"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing field",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fields"
                ],
                "summary": "Update Field",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Field ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Field input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateFieldRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Field"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing field",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fields"
                ],
                "summary": "Delete Field",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Field ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/organizations": {
            "get": {
                "description": "Retrieve all organizations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get Organizations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Organization"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new organization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Create Organization",
                "parameters": [
                    {
                        "description": "Organization details",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateOrganizationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/organizations/{id}": {
            "put": {
                "description": "Update an existing organization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Update Organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated organization details",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateOrganizationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Organization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an organization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Delete Organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/organizations/{name}": {
            "get": {
                "description": "Retrieve an organization by its name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get Organization by Name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Organization"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sites": {
            "get": {
                "description": "Retrieves all sites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Get Sites",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Field ID",
                        "name": "fieldId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Site"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new site",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Create Site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Field ID",
                        "name": "fieldId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Site input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sites/{id}": {
            "get": {
                "description": "Retrieves a site by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Get Site by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Site"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing site",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Update Site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Site input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Site"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing site",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Delete Site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/sign-in": {
            "post": {
                "description": "user sign in",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-auth"
                ],
                "summary": "User SignIn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "sign in info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UserSignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/sign-up": {
            "post": {
                "description": "user sign up",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-auth"
                ],
                "summary": "User SignUp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organizationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "sign up info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UserSignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/wellbores": {
            "get": {
                "description": "Retrieves all wellbores",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wellbores"
                ],
                "summary": "Get Wellbores",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Well ID",
                        "name": "wellId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Wellbore"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new wellbore",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wellbores"
                ],
                "summary": "Create Wellbore",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Well ID",
                        "name": "wellId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Wellbore input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateWellboreRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/wellbores/{id}": {
            "get": {
                "description": "Retrieves a wellbore by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wellbores"
                ],
                "summary": "Get Wellbore by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wellbore ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Wellbore"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing wellbore",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wellbores"
                ],
                "summary": "Update Wellbore",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wellbore ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Wellbore input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateWellboreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Wellbore"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing wellbore",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wellbores"
                ],
                "summary": "Delete Wellbore",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wellbore ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/wells": {
            "get": {
                "description": "Retrieves all wells",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wells"
                ],
                "summary": "Get Wells",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site ID",
                        "name": "siteId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Well"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new well",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wells"
                ],
                "summary": "Create Well",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site ID",
                        "name": "siteId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Well input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateWellRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/wells/{id}": {
            "get": {
                "description": "Retrieves a well by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wells"
                ],
                "summary": "Get Well by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Well ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Well"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing well",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wells"
                ],
                "summary": "Update Well",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Well ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Well input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateWellRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Well"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing well",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wells"
                ],
                "summary": "Delete Well",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Well ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Case": {
            "type": "object",
            "properties": {
                "case_description": {
                    "type": "string"
                },
                "case_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "drill_depth": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "pipe_size": {
                    "type": "number"
                }
            }
        },
        "entities.Company": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "division": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Field"
                    }
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "representative": {
                    "type": "string"
                }
            }
        },
        "entities.Design": {
            "type": "object",
            "properties": {
                "actual_date": {
                    "type": "string"
                },
                "cases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Case"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "plan_name": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "trajectories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Trajectory"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "entities.Field": {
            "type": "object",
            "properties": {
                "active_field_unit": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reduction_level": {
                    "type": "string"
                },
                "sites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Site"
                    }
                }
            }
        },
        "entities.Organization": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "companies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Company"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "registeredAt": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.User"
                    }
                }
            }
        },
        "entities.Site": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "number"
                },
                "azimuth": {
                    "type": "number"
                },
                "block": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "field_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "wells": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Well"
                    }
                }
            }
        },
        "entities.Trajectory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "headers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.TrajectoryHeader"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "units": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.TrajectoryUnit"
                    }
                }
            }
        },
        "entities.TrajectoryHeader": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job_number": {
                    "type": "string"
                },
                "kelly_bushing_elev": {
                    "type": "number"
                },
                "profile": {
                    "type": "string"
                },
                "profile_type": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                },
                "structure": {
                    "type": "string"
                },
                "wellhead": {
                    "type": "string"
                },
                "your_ref": {
                    "type": "string"
                }
            }
        },
        "entities.TrajectoryUnit": {
            "type": "object",
            "properties": {
                "azim": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "dogleg": {
                    "type": "number"
                },
                "global_e_coord": {
                    "type": "number"
                },
                "global_n_coord": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "incl": {
                    "type": "number"
                },
                "local_e_coord": {
                    "type": "number"
                },
                "local_n_coord": {
                    "type": "number"
                },
                "md": {
                    "type": "number"
                },
                "sub_sea": {
                    "type": "number"
                },
                "tvd": {
                    "type": "number"
                },
                "vertical_section": {
                    "type": "number"
                }
            }
        },
        "entities.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "registeredAt": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "entities.Well": {
            "type": "object",
            "properties": {
                "active_well_unit": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "universal_well_identifier": {
                    "type": "string"
                },
                "well_number": {
                    "type": "string"
                },
                "wellbores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Wellbore"
                    }
                },
                "working_group": {
                    "type": "string"
                }
            }
        },
        "entities.Wellbore": {
            "type": "object",
            "properties": {
                "average_column_rotation_frequency": {
                    "type": "number"
                },
                "average_hook_load": {
                    "type": "number"
                },
                "average_inlet_flow": {
                    "type": "number"
                },
                "average_torque": {
                    "type": "number"
                },
                "average_weight_on_bit": {
                    "type": "number"
                },
                "bottom_hole_location": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "depth_interval": {
                    "type": "number"
                },
                "designs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Design"
                    }
                },
                "down_static_friction": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "maximum_column_rotation_frequency": {
                    "type": "number"
                },
                "maximum_torque": {
                    "type": "number"
                },
                "maximum_weight_on_bit": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "riser_pressure": {
                    "type": "number"
                },
                "wellbore_depth": {
                    "type": "number"
                }
            }
        },
        "helpers.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "requests.CreateCompanyRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.CreateCompanyRequestBody"
                },
                "organizationID": {
                    "type": "string"
                }
            }
        },
        "requests.CreateCompanyRequestBody": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "division": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "representative": {
                    "type": "string"
                }
            }
        },
        "requests.CreateDesignRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.CreateDesignRequestBody"
                },
                "wellboreID": {
                    "type": "string"
                }
            }
        },
        "requests.CreateDesignRequestBody": {
            "type": "object",
            "properties": {
                "actual_date": {
                    "type": "string"
                },
                "plan_name": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "requests.CreateFieldRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.CreateFieldRequestBody"
                },
                "companyID": {
                    "type": "string"
                }
            }
        },
        "requests.CreateFieldRequestBody": {
            "type": "object",
            "properties": {
                "active_field_unit": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reduction_level": {
                    "type": "string"
                }
            }
        },
        "requests.CreateOrganizationRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "requests.CreateSiteRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.CreateSiteRequestBody"
                },
                "fieldID": {
                    "type": "string"
                }
            }
        },
        "requests.CreateSiteRequestBody": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "number"
                },
                "azimuth": {
                    "type": "number"
                },
                "block": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "requests.CreateWellRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.CreateWellRequestBody"
                },
                "siteID": {
                    "type": "string"
                }
            }
        },
        "requests.CreateWellRequestBody": {
            "type": "object",
            "properties": {
                "active_well_unit": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "universal_well_identifier": {
                    "type": "string"
                },
                "well_number": {
                    "type": "string"
                },
                "working_group": {
                    "type": "string"
                }
            }
        },
        "requests.CreateWellboreRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.CreateWellboreRequestBody"
                },
                "wellID": {
                    "type": "string"
                }
            }
        },
        "requests.CreateWellboreRequestBody": {
            "type": "object",
            "properties": {
                "average_column_rotation_frequency": {
                    "type": "number"
                },
                "average_hook_load": {
                    "type": "number"
                },
                "average_inlet_flow": {
                    "type": "number"
                },
                "average_torque": {
                    "type": "number"
                },
                "average_weight_on_bit": {
                    "type": "number"
                },
                "bottom_hole_location": {
                    "type": "string"
                },
                "depth_interval": {
                    "type": "number"
                },
                "down_static_friction": {
                    "type": "number"
                },
                "maximum_column_rotation_frequency": {
                    "type": "number"
                },
                "maximum_torque": {
                    "type": "number"
                },
                "maximum_weight_on_bit": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "riser_pressure": {
                    "type": "number"
                },
                "wellbore_depth": {
                    "type": "number"
                }
            }
        },
        "requests.UpdateCompanyRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.UpdateCompanyRequestBody"
                },
                "organizationID": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateCompanyRequestBody": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "division": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "representative": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateDesignRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.UpdateDesignRequestBody"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateDesignRequestBody": {
            "type": "object",
            "properties": {
                "actual_date": {
                    "type": "string"
                },
                "plan_name": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateFieldRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.UpdateFieldRequestBody"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateFieldRequestBody": {
            "type": "object",
            "properties": {
                "active_field_unit": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reduction_level": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateOrganizationRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateSiteRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.UpdateSiteRequestBody"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateSiteRequestBody": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "number"
                },
                "azimuth": {
                    "type": "number"
                },
                "block": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateWellRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.UpdateWellRequestBody"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateWellRequestBody": {
            "type": "object",
            "properties": {
                "active_well_unit": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "universal_well_identifier": {
                    "type": "string"
                },
                "well_number": {
                    "type": "string"
                },
                "working_group": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateWellboreRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.UpdateWellboreRequestBody"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateWellboreRequestBody": {
            "type": "object",
            "properties": {
                "average_column_rotation_frequency": {
                    "type": "number"
                },
                "average_hook_load": {
                    "type": "number"
                },
                "average_inlet_flow": {
                    "type": "number"
                },
                "average_torque": {
                    "type": "number"
                },
                "average_weight_on_bit": {
                    "type": "number"
                },
                "bottom_hole_location": {
                    "type": "string"
                },
                "depth_interval": {
                    "type": "number"
                },
                "down_static_friction": {
                    "type": "number"
                },
                "maximum_column_rotation_frequency": {
                    "type": "number"
                },
                "maximum_torque": {
                    "type": "number"
                },
                "maximum_weight_on_bit": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "riser_pressure": {
                    "type": "number"
                },
                "wellbore_depth": {
                    "type": "number"
                }
            }
        },
        "requests.UserSignInRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 64
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "requests.UserSignUpRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/requests.UserSignUpRequestBody"
                },
                "organizationID": {
                    "type": "string"
                }
            }
        },
        "requests.UserSignUpRequestBody": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "surname"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 64
                },
                "name": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 10
                },
                "surname": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "responses.TokenResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expires_at": {
                    "type": "integer"
                },
                "refresh_token_type": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
